[[redirects]]
  from = "https://www.askherald.com/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://askherald.com/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://www.offsi.com/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://offsi.com/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://www.haroldhq.com/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://haroldhq.com/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://www.undertime.co/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://undertime.co/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://heraldhq.netlify.app/*"
  to = "https://www.heraldhq.com/:splat"
  force = true
  status = 301
  
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"